### ISSUE TITLE
Add Const scheduler

### ISSUE THREAD

**Issue by CarloLucibello** [darsnack/ParameterSchedulers.jl#18]
It can be useful to add a dummy scheduler giving a fixed learning rate to be used in a `Sequence` scheduler. See https://github.com/FluxML/Flux.jl/issues/1815 for an application. 

Right now a constant scheduler can be created with `Exp(; λ, γ=1)`

**Comment by darsnack** [comment]
`Sequence` already allows users to pass in a number instead of a schedule. It uses the `at` function as an indirection. But I think defining a `Const` schedule is a clearer approach, so I'll make this change.
